apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: sravan40/first:mypythonappv2
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mysql.sql.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "mydatabase"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
      imagePullSecrets:
        - name: mydockerhubsecret
